# Generated by Django 5.2.17 on 2026-08-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
    ]
