# Generated by Django 5.2.17 on 2026-10-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_source_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='cover_label_en',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt_en',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
