# Generated by Django 5.2.17 on 2026-10-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_add_blog_agent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='impact_en',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
