# Generated by Django 5.2.17 on 2026-10-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_description_en_project_impact_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
